In [21]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
## Datos experimentales
x_list=[1.0,1.3,1.6,1.9,2.2]
y_list=[0.7651977,0.6200860,0.4554022,0.2818186,0.1103623]

n=len(x_list) ##Numero de ptos experimentales 

##construyendo una matriz de nxn ceros para luego llenarla
T=np.zeros((n,n))
print(T)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
#Llenando la diagonal con dos contadores, dos ciclos fr

for i in range (0,n):
    for j in range(0,n):
        if i==j:
            T[i][j]=y_list[j] ##acceder a cada elemento de la matriz
        else:
            continue

# el orden de llenado de la matriz con las diagonales
for k in range(1,n):
##llenando la matriz triangular superior (j!=i j distinto de i)
    for i in range(0,n-1):
        for j in range(1,n):
            if j!=i and j==i+k:
                T[i][j]=(T[i+1][j]-T[i][j-1])/(x_list[j]-x_list[i])
        