In [3]:
import numpy as np

In [4]:
A = np.array( [[0,1,0],[0,0,1],[2,-5,4]] )
#print (A)

#Vector de términos independientes
B=[0,0,0]
B=np.array(B)

In [5]:
#Producto de matrices
def mprod(A,B):
    nA=A.shape[0]
    mA=A.shape[1]
    nB=B.shape[0]
    mB=B.shape[1]

    C=np.zeros((nA,mB))
    
    for i in range(0,nA):
        for j in range(0,mB):
            sum=0
            for k in range(0,mA):
                sum+=A[i][k]*B[k][j]
            C[i][j]=sum
                
    return C
            
    
def mtrace(A):
    n=A.shape[0]
    sum=0
    for i in range(0,n):
        sum+=A[i][i]
    return sum
    
    
#Creando polinomio característico 
def eigenvalue(A):
    AA=mprod(A,A)
    AAA=mprod(A,AA)
    
    a0=1/6*((mtrace(A)**3)+2*mtrace(AAA)-3*mtrace(A)*mtrace(AA))
    a1=-0.5*(mtrace(A)**2-mtrace(AA))
    a2=mtrace(A)
    a3=-1
    
    
    #Encontrando autovalores 
    coefficients = [a3,a2,a1,a0]
    eigenvalues=np.roots(coefficients)  
    
    # Despreciando la parte decimal, EN EL CASO GENERAL, NO SE TIENE EN CUENTA
    # LO SIGUIENTE PORQUE LOS AUTOVALORES PUEDEN SER COMPLEJOS 
    
    #eigen_val_1= np.roots([a3,a2,a1,a0])[0]
    #eigen_val_2= np.roots([a3,a2,a1,a0])[1]
    #eigen_val_3= np.roots([a3,a2,a1,a0])[2]
    
    #eigenvalues=[eigen_val_1.real,eigen_val_2.real,eigen_val_3.real]
            
    #forma corta
    eigenvalues=np.real(np.roots(coefficients))
    
    return eigenvalues


print(eigenvalue(A)) ##  valores propios de A

[2. 1. 1.]


In [6]:
def row_pivote(A,fil,col):
    max_value=max(A[fil:,col])
    min_value=min(A[fil:,col])
    if(abs(max_value)>abs(min_value)):
        piv=max_value
    else:
        piv=min_value
    for i in range(0,A.shape[0]):
        if A[i][col]==piv:
            row_pivote=i
            break
    
    return row_pivote

In [7]:
def GaussSolver(A,B):
    #Dimensiones de la matriz de coeficientes
    n=A.shape[0]
    m=A.shape[1]
    
    #Creando matriz aumentada
    AB=np.zeros((n,m+1))
    AB[:,0:m]=A
    for i in range(0,len(B)):
        AB[i][m]=B[i]
       
    #Inicia eliminación Gaussiana
    i=0 #Fila inicial
    j=0 #Columna inicial
    s=0 #Número de intercambio de filas (swap)
    #Recorriendo columnas
    for h in range(j,m-1): #Notar que no se trabaja sobre última columna de A
        fila_pivote=row_pivote(AB,i,h)  
        pivote=AB[fila_pivote,h]
        if(fila_pivote!=i):
            #Intercambiando filas
            AB[[i,fila_pivote]]=AB[[fila_pivote,i]]
            s+=1
            #Luego de esto, la fila pivote está en la posición i-ésima
        for k in range(i+1,n):
            x=-AB[k][h]/pivote
            AB[k]=AB[k]+AB[i]*x
        i=i+1
        j=j+1
        
    return AB

In [15]:
def eigenvector(A,eigenvalue):
    #Creando matriz (A-eigenvalue*1)*x=0
    matrix=A-eigenvalue*np.identity(3)
    x=np.array([0,0,0])
    return(GaussSolver(matrix,x))   

In [16]:
print (eigenvector(A,2))

[[-2.  1.  0.  0.]
 [ 0. -4.  2.  0.]
 [ 0.  0.  0.  0.]]
