# Operaciones basicas con matrices

In [2]:
import numpy as np

In [3]:
#A = [[1,2,3],[4,5,6],[6,7,8]]
#A = np.array(A)                                 ##Convirtiendo en arreglo a A

#print(A)

In [10]:
## para sumar

A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,2,3],[4,5,6],[6,7,8]]

A = np.array(A)  
B = np.array(B) 
                                                        ##shape retorna la dimensión de la matriz nxn
def msum(A,B):
    if (A.shape == B.shape):                            ## Asegurandose que las dimensiones sean la misma
        C = np.zeros(A.shape)                        # creando una matriz de ceros para llenar con la suma   
        
          
        for i in range (0,A.shape[0]):        # Llenando las filas desde cero hasta el numero de filas de A    
            for j in range (0,A.shape[1]):    # Llenando las columnas desde cero hasta el numero de colum de A      
                C[i][j]= A[i][j]+B[i][j]          
    return C
    
    
print (A.shape)                              ## muestra la dimension (m , n) donde m filas, n columnas 
print (msum(A,B))

(3, 3)
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [13. 15. 17.]]


In [11]:
## Para obtener la traza, suma de los elementos de la diagonal

def Traza(A):
    if A.shape[0]==A.shape[1]:
        sum = 0
        for i in range(A.shape[0]):
                sum+=A[i][i]
    return sum

print(Traza(A))

15


In [13]:
##Para obetener la transpuesta, invertir el orden entre filas y columnas

def Traspuesta(A):
    ATransp=np.zeros((A.shape[0],A.shape[1]))
    if A.shape[0]==A.shape[1]:
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                ATransp[i][j]=A[j][i]
        return ATransp
    
print(Traspuesta(A))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
