In [2]:
import numpy as np


In [15]:
# Definiendo matriz de coeficientes y vector de terminos indeendientes

A = [[1,1,1],[2,-3,-4],[1,-1,1]] ##priemero las creamos como una lista y se convierte a arreglo
A = np.array(A)

B = [1,9,-1]
B = np.array(B)

In [16]:
## extraer de esa atriz solo la col 2

print(A)
print (A[:,1:]) ## izquierda de la coma filas,  derecha col


#cambiar la posicion de filas Intercambiando las filas

A[[0,1]] = A[[1,0]]

[[ 1  1  1]
 [ 2 -3 -4]
 [ 1 -1  1]]
[[ 1  1]
 [-3 -4]
 [-1  1]]


In [17]:
## crear una rutina que me encuentre la fila en la que esta el pivote 
## esta funcion retorna la fila en la que se encuentra el pivote de una columna

def row_pivote(A,fil,col):       ## depende tambien de la fila pues luego no se considera la primera fila
    
    max_value = max(A[fil:,col])
    min_value = min(A[fil:,col])
    if(abs(max_value)>abs(min_value)):
        
        pivote = min_value
    else:
        pivote = min_value
    #obteniendo el indice del pivote 
    
    for i in range (0,A.shape[0]):
        if(A[i][col]==pivote):
            fila_pivote=i
    return fila_pivote

print (row_pivote(A,0,0))        ##devuelve el indicie de la fila donde esta el pivote

2


In [18]:
def GaussSolver(A,b):
    #DImensiones de la matriz de coeficientes
    n = A.shape[0] #numero de ecuaciones
    m = A.shape[1] #Numero de variables
    
    ##construyendo Mtriz aumentada
    AB = np.zeros((n,m+1))
    AB[:,0:m]=A


    for i in range (0,len(b)): ##recorre en las filas
        AB[i][m] = b[i]
    
   ##inicia eliminacion gaussiana 
    
    i=0     # Contador sobre las filas
    j=0     # COntador sobre las columnas
                    
    ##Se recorre la matriz de izq a der 
    ##recorriendo columnas               

    for h in range(j,m-1):  ##hasta m-1 porque no se usa la ultima col al terminar
        #DEterminadno la fila 
        fila_pivote = row_pivote(AB,i,h)  #fila viene dada por i y columna en el for dada por h
        #determminando el pivote
        pivote = AB[fila_pivote][h]
        
        #analizando la ubicacion del pivote, moviendo la fila del pivote a la posicion mas alta posible
        if (fila_pivote!=i):
            #Genereando intercambio de filas
            AB[[fila_pivote,i]]= AB[[i,fila_pivote]]
            #luego de esto el pivotre e esta en a fila iesima
            
        for k in range(i+1,n):
            x = -AB[k][h]/pivote ##factor x=-a/pivote que multiplica a la fila que tiene el pivote
            ## luego tomar la fila que tiene el pivote y mult por factor x
            AB [k] = AB [k]+x*AB[i]
            
        j = j+1
        i = i+1
        
        #Vector solucion
        
    return AB

print (GaussSolver(A,B))

[[  1.  -1.   1.  -1.]
 [  0.  -1.  -6.   3.]
 [  0.   0. -12.  16.]]
